export const ITEM_IDS = {
  CAT_3017: "cat-3017",
  JD_50P: "jd-50p",
  CAT_3075: "cat-3075",
  BOXER: "boxer",
  CAT_239: "cat-239",
  CAT_265: "cat-265",
  JD_333P: "jd-333p",
  TELEHANDLER: "telehandler",
  FORKLIFT: "forklift",
  MATERIAL_LIFT: "material-lift",
  GENIE_Z45: "genie-z45",
  JLG_ET500J: "jlg-et500j-towable-50-boom-lift",
  GS1930: "genie-gs1930",
  GS3246: "genie-gs3246",
  PRESSURE_WASHER: "pressure-washer",
  SURFACE_CLEANER: "surface-cleaner",
  SNAKE: "ridgid-k400-drain-snake",
  EEL: "electric-eel-commercial-drain-cleaner",
  ROTARY_HAMMER: "rotary-hammer-drill",
  STUMP_GRINDER: "stump-grinder",
  TRASH_PUMP: "trash-pump",
  SUMP_PUMP: "sump-pump",
  GAS_COMPRESSOR: "gas-compressor",
  PANCAKE: "portable-pancake-compressor",
  SPLITTER: "log-splitter",
  CAT_MULCHER: "cat-hm316-mulcher",
  JD_MULCHER: "jd-mh60d-mulcher",
  AUGER: "skid-steer-auger",
  BLUE_DIAMOND_AUGER: "blue-diamond-ex2-mini-skid-auger",
  STIHL_BT131_AUGER: "stihl-bt131-auger",
  BREAKER: "demolition-hammer-skid-steer-or-excavator",
  POWER_RAKE: "power-rake",
  BRUSHCAT: "bobcat-brushcat-60-high-flow-brush-cutter",
  GRAPPLE: "grapple",
  BOX_BLADE: "ignite-3-point-72-box-blade",
  SCAFFOLDING_TOWER: "2-story-mobile-baker-scaffolding-tower",
  SCAFFOLDING: "scaffolding-w-aluminum-platforms",
  DITCH_WITCH_C30X: "ditch-witch-c30x",
  DUMP_TRAILER_25K: "dump-trailer-25-25klb-gvwr",
  ZERO_TURN: "zero-turn-spartan-rt-hd-61-commercial-mower",
  BILLY_GOAT: "billy-goat-bc2601hh-pivot-deck-brush-cutter",
  LAND_PRIDE_BUSH_HOG: "land-pride-rfc-3096-8-bush-hog",
  TILLER: "troy-bilt-horse-rear-tine-tiller",
  CONCRETE_MIXER: "9-cubic-ft-towable-concrete-mixer",
  FLOOR_BUFFER: "prolux-20-commercial-floor-buffer-scrubber-polisher-sander",
  PLATE_COMPACTOR: "6-5-hp-honda-reverse-hydraulic-plate-compactor",
  TILE_SAW: "ridgid-10-wet-tile-saw",
  POST_DRIVER_2_CYCLE: "2-cycle-post-driver",
  TR_89305_JACKHAMMER: "tr-89305-jackhammer",
  SMALL_TRENCHER: "18-trencher-not-self-propelled",
  ROTARY_LASER_LEVEL: "rotary-laser-level",
  JOHN_DEERE_TRACTOR_BACKHOE: "john-deere-tractor-backhoe",
  DIAMOND_CORE_DRILL: "diamond-core-drilling-machine-1-10-bits",
  AIR_MOVER: "b-air-professional-1-2-hp-air-mover",
  FENCE_POST_POUNDER: "fence-post-pounder-skid-steer-or-excavator",
  DUMPSTER: "maxx-d-20-yard-dumpster",
  LIFT_KING_8K: "lift-king-8k-4x4-forklift",
  CONCRETE_SAW: "concrete-saw",
  SCREED: "power-screed",
  TROWEL: "power-trowel",
  VIBRATOR: "concrete-vibrator",
  BULL_FLOAT: "bull-float"
};

export const MULCHER_COMBOS = {
  cat: [ITEM_IDS.CAT_MULCHER, ITEM_IDS.CAT_265],
  jd: [ITEM_IDS.JD_MULCHER, ITEM_IDS.JD_333P]
};

export const EQUIPMENT = {
  [ITEM_IDS.CAT_3017]: { name: "CAT 301.7 Mini Excavator", category: "excavator", day: 385, protection: true, delivery: true, keyword: "CAT 301.7", aliases: ["301.7", "3017", "cat 301.7", "cat301.7", "cat 3017", "cat3017", "mini excavator", "mini ex", "small excavator"], details: "18-inch bucket with 12-inch optional bucket, hydraulic thumb, open cab.", thumb: "Yes, the CAT 301.7 has a hydraulic thumb.", weight: 4222 },
  [ITEM_IDS.JD_50P]: { name: "John Deere 50P Excavator", category: "excavator", day: 495, protection: true, delivery: true, keyword: "John Deere 50P", aliases: ["50p", "50 p", "jd50p", "jd 50p", "john deere 50p", "deere 50p", "mid size excavator"], details: "36-inch bucket, enclosed cab.", thumb: "Yes, the John Deere 50P does have a thumb.", weight: 11349 },
  [ITEM_IDS.CAT_3075]: { name: "CAT 307.5 Excavator", category: "excavator", day: 660, protection: true, delivery: true, keyword: "CAT 307.5", aliases: ["307.5", "3075", "307 5", "cat 307.5", "cat307.5", "cat 3075", "cat3075", "bigger excavator", "full size excavator"], details: "24-inch bucket, hydraulic thumb, enclosed cab, 17,905 lb.", thumb: "Yes, the CAT 307.5 has a hydraulic thumb.", weight: 17905 },

  [ITEM_IDS.BOXER]: { name: "Boxer Mini Skid Steer", category: "skid_steer", day: 330, protection: true, delivery: true, keyword: "Boxer Mini Skid Steer", aliases: ["boxer", "mini skid", "mini skid steer", "ride on skid", "walk behind skid steer", "stand on skid steer"], details: "Bucket is included." },
  [ITEM_IDS.CAT_239]: { name: "CAT 239", category: "skid_steer", day: 440, protection: true, delivery: true, keyword: "CAT 239", aliases: ["239", "cat 239", "cat239", "small cat skid steer", "smaller skid steer"], details: "Open cab.", weight: 7430 },
  [ITEM_IDS.CAT_265]: { name: "CAT 265", category: "skid_steer", day: 550, protection: true, delivery: true, keyword: "CAT 265", aliases: ["265", "cat 265", "cat265", "high flow cat skid steer", "cat high flow skid steer", "high flow skid steer"], details: "74 hp, 10,492 lb, closed cab with AC, high flow.", weight: 10492 },
  [ITEM_IDS.JD_333P]: { name: "John Deere 333P", category: "skid_steer", day: 660, protection: true, delivery: true, keyword: "John Deere 333P", aliases: ["333p", "333 p", "jd333p", "jd 333p", "john deere 333p", "deere 333p", "john deere skid steer"], details: "108.5 hp, 12,183 lb.", weight: 12183 },

  [ITEM_IDS.TELEHANDLER]: { name: "JLG 6K Telehandler", category: "material_handling", day: 723.8, week: 1556.5, month: 3650, protection: true, delivery: true, keyword: "telehandler", aliases: ["telehandler", "telehandlers", "lull", "lulls", "reach forklift", "jlg 6k telehandler", "6k telehandler"], details: "6,000 lb capacity, 42 ft 4 in lift height." },
  [ITEM_IDS.FORKLIFT]: { name: "Mitsubishi Forklift", category: "material_handling", day: 385, protection: true, delivery: true, keyword: "forklift", aliases: ["forklift", "forklifts", "mitsubishi forklift", "warehouse forklift", "standard forklift", "indoor forklift"], details: "3,150 lb capacity, 17 ft lift height." },
  [ITEM_IDS.LIFT_KING_8K]: { name: "Lift King 8K 4x4 Forklift", category: "material_handling", day: 550, week: 2200, protection: true, delivery: true, keyword: "Lift King 8K 4x4 Forklift", aliases: ["lift king", "liftking", "rough terrain forklift", "rough ground forklift", "8k forklift", "8000 lb forklift", "4x4 forklift", "off road forklift", "outdoor forklift", "all terrain forklift"], details: "8,000 lb capacity, 14 ft lift height." },
  [ITEM_IDS.MATERIAL_LIFT]: { name: "Sumner Contractor Lift", category: "material_handling", day: 110, keyword: "Sumner Contractor Lift", aliases: ["contractor lift", "duct lift", "material lift", "sheetrock lift"], details: "Manual lift, 16 ft max height, 650 lb capacity." },
  [ITEM_IDS.SCAFFOLDING_TOWER]: { name: "2-Story Mobile Baker Scaffolding Tower with Outriggers, Guard Rail, and Platform", category: "material_handling", day: 93.5, week: 374, keyword: "2-Story Mobile Baker Scaffolding Tower", aliases: ["scaffolding", "bakers scaffolding", "baker scaffolding", "indoor scaffolding", "painters scaffolding", "mobile scaffolding"], details: "2-story mobile baker scaffolding tower with outriggers, guard rail, and platform." },
  [ITEM_IDS.SCAFFOLDING]: { name: "Scaffolding w/aluminum platforms", category: "material_handling", day: 93.5, week: 374, keyword: "Scaffolding w/aluminum platforms", aliases: ["scaffolding", "outdoor scaffolding", "aluminum platform scaffolding"], details: "Scaffolding with aluminum platforms." },

  [ITEM_IDS.GENIE_Z45]: { name: "Genie Z45 Articulating Boom Lift", category: "boom_lift", day: 471, week: 1884, protection: true, delivery: true, keyword: "Genie Z45 boom lift", aliases: ["genie z45", "z45", "boom lift", "boom lifts", "man lift", "man lifts", "articulating boom", "articulating boom lift"], details: "Articulating boom lift." },
  [ITEM_IDS.JLG_ET500J]: { name: "JLG ET500J Towable 50' Boom Lift", category: "boom_lift", day: 440, week: 1760, protection: true, delivery: true, keyword: "JLG ET500J Towable 50' Boom Lift", aliases: ["jlg et500j", "et500j", "towable boom", "towable boom lift", "towable 50 boom lift", "towable man lift", "tow behind boom", "towable lift", "man lift"], details: "Towable 50-foot boom lift." },
  [ITEM_IDS.GS1930]: { name: "Genie GS1930 Scissor Lift", category: "scissor_lift", day: 192, week: 550, month: 715, protection: true, delivery: true, keyword: "Genie GS1930 Scissor Lift", aliases: ["gs1930", "genie gs1930", "1930 scissor lift", "small scissor lift", "slab scissor lift", "flat surface scissor lift"], details: "Indoor/outdoor slab scissor lift. Not a rough-terrain scissor lift." },
  [ITEM_IDS.GS3246]: { name: "Genie GS3246 Scissor Lift", category: "scissor_lift", day: 313, week: 660, month: 1320, protection: true, delivery: true, keyword: "Genie GS3246 Scissor Lift", aliases: ["gs3246", "genie gs3246", "3246 scissor lift", "larger slab scissor lift", "bigger scissor lift"], details: "Indoor/outdoor slab scissor lift. Not a rough-terrain scissor lift." },

  [ITEM_IDS.PRESSURE_WASHER]: { name: "Pressure Washer", category: "small_tool", day: 85, keyword: "pressure washer", aliases: ["pressure washer", "pressure washers", "power washer", "power washers"], details: "Pressure washer." },
  [ITEM_IDS.SURFACE_CLEANER]: { name: "Surface Cleaner", category: "small_tool", day: 38.5, keyword: "surface cleaner", aliases: ["surface cleaner", "driveway cleaner", "sidewalk cleaner", "flatwork cleaner"], details: "Flatwork surface cleaner." },
  [ITEM_IDS.SNAKE]: { name: "Ridgid K400 Drain Snake", category: "small_tool", day: 93.5, keyword: "Ridgid K400", aliases: ["drain snake", "drain snakes", "snake machine", "k400", "k-400", "ridgid k400", "small drain cleaner"], details: "Good for many standard drain jobs." },
  [ITEM_IDS.EEL]: { name: "Electric Eel Commercial Drain Cleaner", category: "small_tool", day: 137.5, keyword: "Electric Eel", aliases: ["electric eel", "commercial drain cleaner", "heavy drain cleaner", "large drain snake", "big drain cleaner", "commercial snake"], details: "Better for heavier drain jobs." },
  [ITEM_IDS.ROTARY_HAMMER]: { name: 'Makita 1-9/16" Rotary Hammer Drill', category: "small_tool", day: 71.5, keyword: "rotary hammer drill", aliases: ["hammer drill", "rotary hammer", "rotary hammer drill", "makita hammer drill", "sds max drill", "concrete hammer drill"], details: "Takes SDS Max bits. Some bits are included." },
  [ITEM_IDS.STUMP_GRINDER]: { name: "Rayco RG37 Stump Grinder", category: "small_tool", day: 357.5, protection: true, delivery: true, keyword: "stump grinder", aliases: ["stump grinder", "rayco rg37", "rg37", "stump machine", "grind a stump"], details: "Rental Protection Plan is required on that machine." },
  [ITEM_IDS.TRASH_PUMP]: { name: "Trash Pump", category: "small_tool", day: 88, keyword: "trash pump", aliases: ["trash pump", "water pump", "pump out water", "pump a pond", "drain pool", "pump pool"], details: "2-inch semi-trash pump." },
  [ITEM_IDS.SUMP_PUMP]: { name: "Sump Pump", category: "small_tool", day: 93.5, keyword: "sump pump", aliases: ["sump pump", "submersible sump pump", "submersible pump"], details: "Submersible sump pump." },
  [ITEM_IDS.GAS_COMPRESSOR]: { name: "Gas Air Compressor", category: "small_tool", day: 71.5, keyword: "gas air compressor", aliases: ["gas air compressor", "gas compressor", "towable compressor", "air compressor"], details: "Gas-powered air compressor." },
  [ITEM_IDS.PANCAKE]: { name: "Portable Pancake Compressor", category: "small_tool", day: 35, week: 140, keyword: "Portable Pancake Compressor", aliases: ["pancake compressor", "portable compressor", "small compressor", "compressor", "compresser", "electric compressor", "indoor compressor"], details: "Portable pancake compressor." },
  [ITEM_IDS.SPLITTER]: { name: "Log Splitter", category: "small_tool", day: 99, keyword: "log splitter", aliases: ["log splitter", "split wood", "split logs", "firewood splitter", "wood splitter"], details: "Log splitter." },
  [ITEM_IDS.ZERO_TURN]: { name: "Zero Turn Spartan RT-HD 61' Commercial Mower", category: "small_tool", day: 220, week: 880, delivery: true, keyword: "Zero Turn Spartan RT-HD 61' Commercial Mower", aliases: ["mower", "lawn mower", "spartan mower", "spartan", "grass cutter", "zero turn mower", "zero turn"], details: "61-inch commercial zero-turn mower." },
  [ITEM_IDS.TILLER]: { name: "Troy-Bilt Horse rear tine tiller", category: "small_tool", day: 82.5, keyword: "Troy-Bilt Horse rear tine tiller", aliases: ["tiller", "rear tine tiller", "walk behind tiller"], details: "Rear tine tiller." },
  [ITEM_IDS.FLOOR_BUFFER]: { name: "Prolux 20' Commercial Floor Buffer Scrubber/Polisher/Sander", category: "small_tool", day: 93.5, week: 374, keyword: "Prolux 20 Commercial Floor Buffer", aliases: ["floor sander", "floor buffer", "floor scrubber", "polisher"], details: "Commercial floor buffer/scrubber/polisher/sander." },
  [ITEM_IDS.ROTARY_LASER_LEVEL]: { name: "Rotary Laser Level", category: "small_tool", day: 50, week: 200, keyword: "Rotary Laser Level", aliases: ["laser level", "rotary laser level", "laser"], details: "Rotary laser level." },
  [ITEM_IDS.AIR_MOVER]: { name: "B-Air Professional 1/2 HP Air Mover", category: "small_tool", day: 50, week: 200, keyword: "B-Air Professional Air Mover", aliases: ["air mover", "floor fan", "floor fans", "drying fan", "carpet blower"], details: "Professional 1/2 HP air mover." },
  [ITEM_IDS.DUMPSTER]: { name: "Maxx-D 20 Yard Dumpster", category: "small_tool", day: 500, week: 500, keyword: "20 yard dumpster", aliases: ["dumpster", "dumpsters", "roll off dumpster", "roll off dumpsters", "roll off", "roll offs"], details: "20-yard roll-off dumpster." },

  [ITEM_IDS.CAT_MULCHER]: { name: "CAT HM316 Forestry Mulcher", category: "attachment", day: 610, protection: true, keyword: "CAT HM316 Forestry Mulcher", aliases: ["cat mulcher", "cat hm316", "hm316", "hm316 mulcher", "cat hm 316", "cat forestry mulcher", "forestry mulcher"], details: "Uses carbide teeth that do not need sharpening. High Flow XPS required. Can be rented by itself or paired with the CAT 265 only." },
  [ITEM_IDS.JD_MULCHER]: { name: "John Deere MH60D Forestry Mulcher", category: "attachment", day: 610, protection: true, keyword: "John Deere MH60D Forestry Mulcher", aliases: ["john deere mulcher", "jd mulcher", "mh60d", "mh60d mulcher", "john deere mh60d", "jd mh60d", "john deere forestry mulcher", "forestry mulcher"], details: "Removes up to 8-inch trees and 12-inch stumps. Can be rented by itself or paired with the John Deere 333P only." },
  [ITEM_IDS.AUGER]: { name: "Skid Steer Auger", category: "attachment", day: 225, keyword: "Skid Steer Auger", aliases: ["skid steer auger", "auger attachment", "auger", "post hole auger", "post hole digger"], details: "Bits rented separately. Attachment can be rented separately." },
  [ITEM_IDS.BLUE_DIAMOND_AUGER]: { name: "Blue Diamond EX2 Mini Skid Auger", category: "attachment", day: 100, week: 400, keyword: "Blue Diamond EX2 Mini Skid Auger", aliases: ["blue diamond", "blue diamond auger", "mini skid auger", "auger", "boxer auger"], details: "Mini skid auger. 10, 12, or 18-inch bit rented separately." },
  [ITEM_IDS.STIHL_BT131_AUGER]: { name: "Stihl BT131 Auger", category: "attachment", day: 85, week: 340, keyword: "Stihl BT131 Auger", aliases: ["stihl", "bt131", "stihl bt131", "auger", "handheld auger", "hand held auger", "one person auger", "stihl auger"], details: "Stihl BT131 handheld auger." },
  [ITEM_IDS.BREAKER]: { name: "Demolition Hammer Skid Steer or Excavator", category: "attachment", day: 350, week: 1000, keyword: "Demolition Hammer Skid Steer or Excavator", aliases: ["skid steer breaker", "skid steer concrete breaker", "skid steer jackhammer", "skid steer jack hammer", "skid steer demolition hammer", "breaker attachment", "breaker", "hydraulic breaker", "hydraulic hammer", "skid steer hammer", "demolition hammer attachment", "demolition hammer", "demo hammer attachment", "skid steer demo hammer", "concrete breaker attachment", "concrete breaker", "excavator breaker", "excavator hammer", "jackhammer attachment", "jack hammer attachment"], details: "Demolition hammer attachment for skid steer or excavator." },
  [ITEM_IDS.POWER_RAKE]: { name: "Power Rake", category: "attachment", day: 225, keyword: "Power Rake", aliases: ["power rake", "harley rake", "harley", "soil conditioner", "soil prep attachment"], details: "Attachment can be rented separately." },
  [ITEM_IDS.BRUSHCAT]: { name: "Bobcat Brushcat 60 High Flow Brush Cutter", category: "attachment", day: 275, week: 1100, month: 1500, keyword: "Bobcat Brushcat 60 High Flow Brush Cutter", aliases: ["brushcat", "brushcat 60", "skid steer brush cutter", "brush cutter attachment", "brush cutter", "bush hog", "rotary cutter"], details: "High-flow skid steer brush cutter attachment." },
  [ITEM_IDS.GRAPPLE]: { name: "Grapple", category: "attachment", day: 110, keyword: "Grapple", aliases: ["grapple", "root grapple", "brush grapple", "tree grapple"], details: "Attachment can be rented separately." },
  [ITEM_IDS.BOX_BLADE]: { name: "Ignite 3 Point 72 Box Blade", category: "attachment", day: 200, week: 800, month: 1100, keyword: "Ignite 3 Point 72 Box Blade", aliases: ["box blade", "3 point box blade", "3pt box blade"], details: "72-inch 3-point box blade." },
  [ITEM_IDS.BILLY_GOAT]: { name: "Billy Goat BC2601HH Pivot Deck Brush Cutter", category: "attachment", day: 137.5, week: 550, keyword: "Billy Goat BC2601HH", aliases: ["billy goat", "brush cutter", "walk behind bush hog", "walk behind brush cutter", "manual brush cutter"], details: "Walk-behind brush cutter." },
  [ITEM_IDS.LAND_PRIDE_BUSH_HOG]: { name: "Land Pride RFC 3096 8' Bush Hog", category: "attachment", day: 220, week: 880, keyword: "Land Pride RFC 3096 8' Bush Hog", aliases: ["land pride", "bush hog", "brush cutter", "rotary cutter", "tractor bush hog", "3 pt bush hog", "3pt bush hog", "8 foot bush hog"], details: "8-foot tractor bush hog." },
  [ITEM_IDS.JOHN_DEERE_TRACTOR_BACKHOE]: { name: "John Deere Tractor & Backhoe", category: "attachment", day: 385, week: 1540, protection: true, delivery: true, keyword: "John Deere Tractor & Backhoe", aliases: ["tractor", "backhoe", "back hoe", "small tractor", "tractor with bucket", "tractor and grapple", "tractor with grapple"], details: "John Deere tractor with backhoe." },
  [ITEM_IDS.FENCE_POST_POUNDER]: { name: "Fence Post Pounder (Skid steer or Excavator)", category: "attachment", day: 350, week: 1000, keyword: "Fence Post Pounder", aliases: ["fence pounder", "post pounder", "fence post pounder", "pole pounder", "skid steer post pounder"], details: "Fence post pounder for skid steer or excavator." },

  [ITEM_IDS.DITCH_WITCH_C30X]: { name: "Ditch Witch C30X", category: "small_tool", day: 250, week: 1000, protection: true, delivery: true, keyword: "Ditch Witch C30X", aliases: ["trencher", "ditch witch", "c30x", "trenchers", "ditcher"], details: "Ditch Witch C30X trencher." },
  [ITEM_IDS.SMALL_TRENCHER]: { name: "18' Trencher (not self-propelled)", category: "small_tool", day: 125, keyword: "18 inch trencher", aliases: ["trencher", "walk behind trencher", "small trencher", "18 trencher", "18 inch trencher", "pull behind trencher"], details: "18-inch trencher. Not self-propelled." },

  [ITEM_IDS.CONCRETE_SAW]: { name: "Concrete Saw", category: "small_tool", day: 150, keyword: "concrete saw", aliases: ["concrete saw", "cut off saw", "cutoff saw", "stihl saw", "demo saw"], details: "Blade is sold separately." },
  [ITEM_IDS.CONCRETE_MIXER]: { name: "9 cubic ft Towable Concrete Mixer", category: "small_tool", day: 80, week: 320, keyword: "9 cubic ft Towable Concrete Mixer", aliases: ["concrete mixer", "towable mixer", "towable concrete mixer", "gas powered mixer"], details: "9 cubic foot towable concrete mixer." },
  [ITEM_IDS.SCREED]: { name: "Power Screed", category: "small_tool", day: 137.5, keyword: "Power Screed", aliases: ["power screed", "screed", "vibrating screed", "concrete screed"], details: "Screed board rented separately." },
  [ITEM_IDS.TROWEL]: { name: "Power Trowel", category: "small_tool", day: 135, keyword: "Power Trowel", aliases: ["power trowel", "walk behind trowel", "concrete trowel"], details: "Power trowel." },
  [ITEM_IDS.VIBRATOR]: { name: "Concrete Vibrator", category: "small_tool", day: 49, keyword: "Concrete Vibrator", aliases: ["concrete vibrator", "cement vibrator", "pencil vibrator"], details: "Concrete vibrator." },
  [ITEM_IDS.BULL_FLOAT]: { name: "Bull Float", category: "small_tool", day: 35, keyword: "Bull Float", aliases: ["bull float", "concrete float"], details: "Bull float." },
  [ITEM_IDS.PLATE_COMPACTOR]: { name: "6.5 HP Honda Reverse Hydraulic Plate Compactor", category: "small_tool", day: 100, week: 400, keyword: "Honda Reverse Hydraulic Plate Compactor", aliases: ["compactor", "walk behind compactor", "asphalt compactor", "plate compactor"], details: "Reverse hydraulic plate compactor for asphalt, aggregate, and cohesive soil compaction." },
  [ITEM_IDS.TILE_SAW]: { name: "Ridgid 10 Wet Tile Saw with Stand", category: "small_tool", day: 75, week: 300, keyword: "Ridgid 10 Wet Tile Saw", aliases: ["tile saw", "wet saw", "ridgid tile saw"], details: "10-inch wet tile saw with stand. Diamond blade sold separately." },
  [ITEM_IDS.DIAMOND_CORE_DRILL]: { name: "Diamond Core Drilling Machine (1-10 bits)", category: "small_tool", day: 125, week: 500, keyword: "Diamond Core Drilling Machine", aliases: ["core drill", "hole drill", "diamond core drill", "core drilling machine"], details: "Diamond core drilling machine. 1-10 inch bits." },
  [ITEM_IDS.POST_DRIVER_2_CYCLE]: { name: "2-Cycle Post Driver", category: "small_tool", day: 55, week: 220, keyword: "2-Cycle Post Driver", aliases: ["2 cycle post driver", "2-cycle post driver", "2 cycle post pounder", "2-cycle post pounder", "handheld post driver", "handheld post pounder", "hand held post driver", "hand held post pounder", "manual post driver", "t post driver", "t-post driver", "t post pounder", "t-post pounder", "fence post driver handheld", "fence post pounder handheld"], details: "Handheld 2-cycle fence post driver/pounder." },

  [ITEM_IDS.TR_89305_JACKHAMMER]: { name: "TR-89305 Jackhammer", category: "small_tool", day: 55, week: 220, keyword: "TR-89305 Jackhammer", aliases: ["tr-89305", "tr89305", "89305", "tr 89305", "jack hammer", "jackhammer", "handheld jackhammer", "handheld jack hammer", "hand held jackhammer", "hand held jack hammer", "electric jackhammer", "electric jack hammer", "demo hammer", "handheld demo hammer", "demolition hammer", "handheld demolition hammer", "concrete breaker"], details: "Handheld jackhammer." },

  [ITEM_IDS.DUMP_TRAILER_25K]: { name: "Dump Trailer 25' 25K GVWR", category: "trailer", day: 440, week: 1760, month: 4000, keyword: "Dump Trailer 25 25K GVWR", aliases: ["dump trailer", "gooseneck dump trailer", "25k dump trailer", "25 foot dump trailer", "trailer"], details: "25-foot dump trailer, 25K GVWR." }
};

export const CATEGORY_ALIASES = {
  excavator: ["excavator", "excavators", "mini excavator", "mini excavators", "trackhoe", "trackhoes", "digger", "digger machine"],
  skid_steer: ["skid steer", "skid steers", "track loader", "track loaders", "compact track loader", "compact track loaders", "ctl"],
  mini_skid: ["mini skid", "mini skid steer", "boxer", "stand on skid steer", "walk behind skid steer"],
  boom_lift: ["boom lift", "boom lifts", "man lift", "man lifts", "articulating boom", "towable boom", "towable man lift"],
  scissor_lift: ["scissor lift", "scissor lifts", "slab scissor lift", "slab scissor lifts", "flat scissor lift", "flat surface scissor lift"],
  forklift: ["forklift", "forklifts", "fork lift", "fork lifts", "warehouse forklift", "rough terrain forklift", "rough ground forklift", "outdoor forklift", "4x4 forklift", "8k forklift"],
  telehandler: ["telehandler", "telehandlers", "lull", "lulls", "reach forklift"],
  material_handling: ["material handling", "material lift", "contractor lift", "scaffolding", "scaffold"],
  scaffolding: ["scaffolding", "scaffold", "scaffolds", "baker scaffolding", "baker scaffold", "mobile scaffolding", "mobile scaffold", "outdoor scaffolding", "outdoor scaffold", "frame scaffolding", "aluminum platform scaffolding"],
  auger: ["auger", "augers", "post hole digger", "post hole auger", "hole auger"],
  post_driver: ["post driver", "post drivers", "post pounder", "post pounders", "fence post pounder", "fence post driver", "handheld post pounder", "handheld post driver", "hand held post pounder", "hand held post driver", "t post driver", "t-post driver", "t post pounder", "t-post pounder", "skid steer post driver"],
  dumpster: ["dumpster", "dumpsters", "roll off", "roll off dumpster", "20 yard dumpster"],
  mower: ["mower", "mowers", "lawn mower", "zero turn", "zero turn mower", "grass cutter"],
  brush_cutter: ["brush cutter", "brush cutters", "bush hog", "bush hogs", "rotary cutter", "walk behind brush cutter"],
  trencher: ["trencher", "trenchers", "ditch witch", "ditch witches", "walk behind trencher"],
  drain_cleaner: ["drain cleaner", "drain cleaners", "drain snake", "drain snakes", "snake machine", "commercial drain cleaner"],
  pressure_washer: ["pressure washer", "pressure washers", "power washer", "power washers"],
  compactor: ["compactor", "compactors", "plate compactor", "walk behind compactor"],
  concrete: ["concrete", "concrete saw", "concrete mixer", "power screed", "trowel", "bull float", "concrete vibrator", "tile saw", "core drill"],
  breaker: ["breaker", "breakers", "concrete breaker", "demolition hammer", "demo hammer", "jack hammer", "jackhammer", "hydraulic breaker", "hydraulic hammer", "skid steer jackhammer", "skid steer jack hammer", "skid steer demolition hammer"],
  trailer: ["trailer", "trailers", "equipment trailer", "dump trailer", "gooseneck"],
  pump: ["pump", "pumps", "trash pump", "sump pump", "water pump"],
  compressor: ["compressor", "compressors", "air compressor", "pancake compressor", "gas compressor"],
  mulcher: ["mulcher", "mulchers", "forestry mulcher", "forestry mulchers", "brush mulcher", "cat mulcher", "john deere mulcher", "jd mulcher", "hm316", "mh60d"],
  small_tool: ["small tool", "small tools", "tool", "tools"]
};

export const CATEGORY_ITEMS = {
  excavator: [ITEM_IDS.CAT_3017, ITEM_IDS.JD_50P, ITEM_IDS.CAT_3075],
  skid_steer: [ITEM_IDS.BOXER, ITEM_IDS.CAT_239, ITEM_IDS.CAT_265, ITEM_IDS.JD_333P],
  mini_skid: [ITEM_IDS.BOXER],
  boom_lift: [ITEM_IDS.GENIE_Z45, ITEM_IDS.JLG_ET500J],
  scissor_lift: [ITEM_IDS.GS1930, ITEM_IDS.GS3246],
  forklift: [ITEM_IDS.FORKLIFT, ITEM_IDS.LIFT_KING_8K],
  telehandler: [ITEM_IDS.TELEHANDLER],
  material_handling: [ITEM_IDS.TELEHANDLER, ITEM_IDS.FORKLIFT, ITEM_IDS.LIFT_KING_8K, ITEM_IDS.MATERIAL_LIFT, ITEM_IDS.SCAFFOLDING_TOWER, ITEM_IDS.SCAFFOLDING],
  scaffolding: [ITEM_IDS.SCAFFOLDING_TOWER, ITEM_IDS.SCAFFOLDING],
  auger: [ITEM_IDS.AUGER, ITEM_IDS.BLUE_DIAMOND_AUGER, ITEM_IDS.STIHL_BT131_AUGER],
  post_driver: [ITEM_IDS.FENCE_POST_POUNDER, ITEM_IDS.POST_DRIVER_2_CYCLE],
  dumpster: [ITEM_IDS.DUMPSTER],
  mower: [ITEM_IDS.ZERO_TURN],
  brush_cutter: [ITEM_IDS.BRUSHCAT, ITEM_IDS.LAND_PRIDE_BUSH_HOG, ITEM_IDS.BILLY_GOAT],
  trencher: [ITEM_IDS.DITCH_WITCH_C30X, ITEM_IDS.SMALL_TRENCHER],
  drain_cleaner: [ITEM_IDS.SNAKE, ITEM_IDS.EEL],
  pressure_washer: [ITEM_IDS.PRESSURE_WASHER, ITEM_IDS.SURFACE_CLEANER],
  compactor: [ITEM_IDS.PLATE_COMPACTOR],
  concrete: [ITEM_IDS.CONCRETE_SAW, ITEM_IDS.CONCRETE_MIXER, ITEM_IDS.SCREED, ITEM_IDS.TROWEL, ITEM_IDS.VIBRATOR, ITEM_IDS.BULL_FLOAT, ITEM_IDS.TILE_SAW, ITEM_IDS.DIAMOND_CORE_DRILL],
  breaker: [ITEM_IDS.BREAKER, ITEM_IDS.TR_89305_JACKHAMMER],
  trailer: [ITEM_IDS.DUMP_TRAILER_25K],
  pump: [ITEM_IDS.TRASH_PUMP, ITEM_IDS.SUMP_PUMP],
  compressor: [ITEM_IDS.GAS_COMPRESSOR, ITEM_IDS.PANCAKE],
  mulcher: [ITEM_IDS.CAT_MULCHER, ITEM_IDS.JD_MULCHER],
  small_tool: [ITEM_IDS.PRESSURE_WASHER, ITEM_IDS.SURFACE_CLEANER, ITEM_IDS.SNAKE, ITEM_IDS.EEL, ITEM_IDS.ROTARY_HAMMER, ITEM_IDS.STUMP_GRINDER, ITEM_IDS.TRASH_PUMP, ITEM_IDS.SUMP_PUMP, ITEM_IDS.GAS_COMPRESSOR, ITEM_IDS.PANCAKE, ITEM_IDS.SPLITTER, ITEM_IDS.ZERO_TURN, ITEM_IDS.TILLER, ITEM_IDS.CONCRETE_SAW, ITEM_IDS.CONCRETE_MIXER, ITEM_IDS.PLATE_COMPACTOR, ITEM_IDS.TILE_SAW, ITEM_IDS.TR_89305_JACKHAMMER, ITEM_IDS.SMALL_TRENCHER, ITEM_IDS.ROTARY_LASER_LEVEL, ITEM_IDS.DIAMOND_CORE_DRILL, ITEM_IDS.AIR_MOVER, ITEM_IDS.DUMPSTER]
};
